version: "3.7"

services:
  frontend-build:
    build:
      context: .
      dockerfile: deploy/docker/frontend/Dockerfile
    command: ["sh", "-c", "yarn install && yarn build"]
    volumes:
      - ./react-ui:/app:cached
      - ./mockrift:/mockrift
      - /app/node_modules
