version: "3.7"

services:
  server:
    build:
      context: .
      dockerfile: deploy/docker/server/Dockerfile
      target: builder
    command: ["modd", "-f", "modd.conf"]
    volumes:
      - ./mockrift:/home/appuser/app
    ports:
      - 3499:3499

  frontend:
    build:
      context: .
      dockerfile: deploy/docker/frontend/Dockerfile
    command: ["sh", "-c", "yarn install && yarn start"]
    volumes:
      - ./react-ui:/app:cached
      - /app/node_modules
    ports:
      - 8080:8080
