version: "3.7"

services:
  server: &server
    build:
      context: .
      dockerfile: deploy/docker/server/Dockerfile
      target: builder
      args:
        go_release: debug
    environment:
      RUN_COMMAND: run
    command: ["make", "run-reflex"]
    volumes:
      - ./mockrift:/home/appuser/app:cached
      - ./mockrift/requests:/home/appuser/app/requests:cached
    ports:
      - 3499:3499
      - 40000:40000

  server-debug:
    <<: *server
    environment:
      RUN_COMMAND: run-delve
