version: "3.7"

services:
  server:
    build:
      context: .
      dockerfile: deploy/docker/server/Dockerfile
      target: builder
      args:
        go_release: debug
    environment:
      GIN_MODE: debug
    command: ["modd", "-f", "modd.conf"]
    volumes:
      - ./mockrift:/home/appuser/app
    ports:
      - 3499:3499
